{{-- Controle de fonte: − A + --}}
<div class="bible-font-control flex items-center rounded-xl border border-gray-200 dark:border-slate-700 overflow-hidden bg-gray-50 dark:bg-slate-800 shrink-0">
    <button type="button" id="bible-font-minus-btn" class="bible-reader-bar-btn inline-flex items-center justify-center w-9 h-10 text-gray-500 dark:text-slate-400 hover:text-indigo-600 dark:hover:text-indigo-400 hover:bg-indigo-50 dark:hover:bg-indigo-900/20 transition-colors touch-manipulation" title="Diminuir fonte" aria-label="Diminuir fonte"><x-icon name="minus" class="w-4 h-4" /></button>
    <span class="bible-font-label px-2 text-xs font-bold text-gray-600 dark:text-slate-300 min-w-[1.5rem] text-center" aria-hidden="true">A</span>
    <button type="button" id="bible-font-plus-btn" class="bible-reader-bar-btn inline-flex items-center justify-center w-9 h-10 text-gray-500 dark:text-slate-400 hover:text-indigo-600 dark:hover:text-indigo-400 hover:bg-indigo-50 dark:hover:bg-indigo-900/20 transition-colors touch-manipulation" title="Aumentar fonte" aria-label="Aumentar fonte"><x-icon name="plus" class="w-4 h-4" /></button>
</div>
<button type="button" id="bible-theme-btn" class="bible-reader-bar-btn inline-flex items-center justify-center w-10 h-10 rounded-xl bg-gray-50 dark:bg-slate-800 border border-gray-200 dark:border-slate-700 text-gray-500 dark:text-slate-400 hover:text-indigo-600 dark:hover:text-indigo-400 hover:bg-indigo-50 dark:hover:bg-indigo-900/20 transition-colors shrink-0" title="Tema de leitura" aria-label="Tema de leitura"><x-icon name="circle-half-stroke" class="w-5 h-5" /></button>
<button type="button" id="bible-line-height-btn" class="bible-reader-bar-btn inline-flex items-center justify-center w-10 h-10 rounded-xl bg-gray-50 dark:bg-slate-800 border border-gray-200 dark:border-slate-700 text-gray-500 dark:text-slate-400 hover:text-indigo-600 dark:hover:text-indigo-400 hover:bg-indigo-50 dark:hover:bg-indigo-900/20 transition-colors shrink-0" title="Espaçamento entre linhas" aria-label="Espaçamento"><x-icon name="paragraph" class="w-5 h-5" /></button>
<button type="button" id="bible-fullscreen-btn" class="bible-fullscreen-btn bible-reader-bar-btn inline-flex items-center justify-center w-10 h-10 rounded-xl bg-gray-50 dark:bg-slate-800 border border-gray-200 dark:border-slate-700 text-gray-500 dark:text-slate-400 hover:text-indigo-600 dark:hover:text-indigo-400 hover:bg-indigo-50 dark:hover:bg-indigo-900/20 transition-colors shrink-0" title="Modo foco" aria-label="Modo foco">
    <span class="bible-fs-enter"><x-icon name="expand" class="w-5 h-5" /></span>
    <span class="bible-fs-exit hidden"><x-icon name="compress" class="w-5 h-5" /></span>
</button>
